### ISSUE TITLE
Meta-issue: cover as much as possible of "A user's guide to the local arithmetic of hyperelliptic curves"

### ISSUE THREAD

**Issue by alexjbest** [alexjbest/cluster-pictures#33]
This issue tracks progress covering as many theorems / algorithms and examples as possible from http://arxiv.org/abs/2007.01749

- [x] Section 3 "Clusters"
  - [x] All notation for clusters
  - [ ] some issues with theta still when extending by sqrt
  - [x] Example 3.6
  - [x] Example 3.7
- [x] Section 4 "BY trees"
  - [x] Definitions
  - [ ] Plotting automorphisms
  - [x] Example 4.9
  - [ ] Example 4.11 not done yet, I think I did it once but its a bit fiddly
  - [ ] Example 4.12 not done
- [ ] Section 5 "Reduction typee"
  - [x] semistability criterion
  - [x] good reduction criterion
  - [x] good reduction jacobian criterion
  - [x] pot. good reduction 
  - [x] pot. toric rank
  - [ ] tame reduction criterion
  - [x] Example 5.8
  - [x] Example 5.10
- [x] Section 6 "special fibre ss"
  - [x] red map
  - [x] component equations
  - [x] dual graph
  - [x] Example 6.9
  - [x] Example 6.10
- [ ] Section 7 "min reg model" nothing done at all
  - [ ] Theorems
  - [ ] Example 7.6
  - [ ] Example 7.7
- [x] Section 8 "dual special fibre and homology" done I think, maybe galois action needs a bit more work
  - [x] Theorem 8.1 have dual_graph which I implement based on section 6, so should be double checked?
  - [x] Theorem 8.2
  - [x] Example 8.4 just added
  - [x] Example 8.5 
  - [x] Example 8.6 
- [ ] Section 9 "snc model, tame" nothing
  - [ ] Theorems
  - [ ] Example 1
  - [ ] Example 2
- [x] Section 10 "tamagawa"
  - [x] Theorems
  - [x] Example 10.4
  - [x] Example 10.5
  - [x] Example 10.6
  - [x] Example 10.7
- [ ] Section 11 "gal reps" nothing, not clear even how to represent the info in sage
  - [ ] Theorems
  - [ ] Example 11.5
  - [ ] Example 11.6
- [ ] Section 12 "conductors"
  - [x] tame conductor
  - [ ] wild conductor not really done as getting the full galois group in the case of a wild field seems hard
  - [x] Example 12.5 (should also check that the wild part returns 0)
  - [ ] Example 12.6 (tame case only)
  - [x] Example 12.7 (should also check that the wild part returns 0)
  - [x] Example 12.8 (should also check that the wild part returns 0)
- [ ] Section 13 "root numbers tame" #27 
  - [ ] theorems (these look doable to me)
  - [ ] Example 13.7 (done using semistable stuff from homology section)
  - [x] Example 13.8 (done using semistable stuff from homology section)
  - [x] Example 13.9 (done using semistable stuff from homology section)
- [x] Section 14 "differentials"
  - [x] Theorems half done
  - [x] Example 14.8
  - [x] Example 14.9
  - [ ] Example 14.10
- [x] Section 15 "min disc"
  - [x] Theorem 15.1, the discriminant function of a cluster
  - [x] Theorem 15.2, the minimal_discriminant function of a cluster
  - [x] notation 15.4, the weight function of a BY_tree
  - [x] Theorem 15.5, the minimal_discriminant function of a BY_tree
  - [x] Example 15.6
  - [ ] Example 15.7 (missing the base changed example, in general our stuff is not well tested over extensions)
- [x] Section 16 "min weier" pretty much done once again the only limitation is that galois action, so we should chcek root field is tame also
  - [x] Theorem 16.1
  - [x] Theorem 16.2
  - [x] Theorem 16.3
  - [x] Example 16.4
  - [x] Example 16.5
  - [x] Example 16.6
  - [x] Example 16.7
- [ ] Section 17 "isomorphisms/ equivalence"
  - [ ] def 17.2, we don't have these operations on cluster pictures, they would be quite easy to do, probably best as a function on a cluster tthat returns an updated one rather than mutating.
  - [ ] theorem 17.5, we have a function to pass from a BY tree to a cluster, but i'm unsure if it is doing exactly the right thing as I dont "attach an open yellow edge to the center"
  - [ ] Example 17.6
  - [ ] Example 17.7
  - [x] Example 17.9
